import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import {Button} from '@chakra-ui/react'
import {EmailIcon} from '@chakra-ui/icons'
import Nav from '../pages/components/Nav'
import Hero from '../pages/components/Hero'
import Footer from '../pages/components/Footer'


export default function Home() {
  return (
    <div className="max-w-max h-screen ">
      <Nav></Nav>
      <Hero></Hero>
      <Footer></Footer>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-3xl text-rose-900'>HELLO</h1>
      <Button className=' text-red-100' leftIcon={<EmailIcon />} colorScheme='teal' variant='outline'>
      Button
      </Button> */}
    </div>
  )
}
